### ISSUE TITLE
Cannot find module './core' in webflow-api/dist/index.js - v1.3.0

### ISSUE THREAD

**Issue by brettwray** [webflow/js-webflow-api#102]
We're on version 1.2.2 however today 1.3.0 was installed by our CI system and it appears there's a bug. 

`Cannot find module './core' in webflow-api/dist/index.js`

Upon inspection of the installed package it appears that the only file in `webflow-api/dist/` is `index.js`.

**Comment by tbell511** [comment]
I have the same exact problem. Downgraded to 1.2.2 for a temp fix.

**Comment by robmarshall** [comment]
Also got this. Reverting to 1.2.2 solved it.

**Comment by dhwanie17** [comment]
Same issue Cannot find module './core' in webflow-api/dist/index.js

**Comment by vipinWednesday** [comment]
> Same issue Cannot find module './core' in webflow-api/dist/index.js

Similar issue with 1.3.0

**Comment by RodneyU215** [comment]
Thanks for reporting this issue. I'll fix this asap.

**Comment by RodneyU215** [comment]
This issue has been resolved. Please use [1.3.1](https://github.com/webflow/js-webflow-api/releases/tag/v1.3.1).
