### ISSUE TITLE
Beta flag not typed?

### ISSUE THREAD

**Issue by DominikRapacki** [webflow/js-webflow-api#108]
I wanted to add the beta flag to transition to v.2 however it is not inside the type definition also in your usage example it is missing.

**Comment by deldrid1** [comment]
+1 for this

```
Argument of type '{ beta: boolean; token: string; }' is not assignable to parameter of type 'WebflowOptions'.
  Object literal may only specify known properties, and 'beta' does not exist in type 'WebflowOptions'.ts(2345)
```

Seems like a small update to `interface WebflowOptions` is needed?

**Comment by dsinghvi** [comment]
@DominikRapacki this should be fixed on the latest sdk! (v2 is now fully typed).
