### ISSUE TITLE
Not able to update fields

### ISSUE THREAD

**Issue by ram-lilbigthings** [webflow/js-webflow-api#115]
We tried to update fields within collection item with new api v2 sdk and we are getting response status as 200. Still when we check webflow item fields they do not get updated there. We are trying to update optimized images using api v2 sdk but they are not getting updated
![issue ss 1](https://github.com/webflow/js-webflow-api/assets/132983628/8a440091-cd0a-4efb-aa49-72f6d7313994) - Here I am attaching code through which we are updating images
![issue ss 2](https://github.com/webflow/js-webflow-api/assets/132983628/866e5ffa-3d5d-4bcb-9b9a-bd1b24fefc0e) - Here I am getting status as 200
![issue ss3 (1)](https://github.com/webflow/js-webflow-api/assets/132983628/024728bb-1ea2-4edb-a0f6-357d842cec7c) - The data which we are sending 
![issue ss 4](https://github.com/webflow/js-webflow-api/assets/132983628/31c24404-5fdb-4b69-a3ac-050872559f24) - The log of image which we optimized we compressed it from 154KB to 139KB and we are trying to upload that 139KB image
![issue ss 5](https://github.com/webflow/js-webflow-api/assets/132983628/3074b7ce-3528-4ca3-9a3a-b0a4769969c8) - We refreshed webflow and checked but in field the image do not get updated.

**Comment by zplata** [comment]
Hi @ram-lilbigthings - apologies for the much-delayed fix here, but if you're still using the JS SDK for your workflows, you can try upgrading to `v2.4.0` which should not strip any additional data you pass into the `fieldData` object.

[Release notes here](https://github.com/webflow/js-webflow-api/releases)

**Comment by dsinghvi** [comment]
@ram-lilbigthings closing this issue, but please reopen if you are still blocked!
