### ISSUE TITLE
Wrong node-fetch import in Fetcher

### ISSUE THREAD

**Issue by jakubchadim** [webflow/js-webflow-api#140]
My nextJS API is failing that import require("node-fetch") is not a function. It needs to be imported as require("node-fetch").default in Fetcher.

**Comment by jakubchadim** [comment]
One possible fix would be `require("node-fetch")?.default ?? require("node-fetch")`

**Comment by zplata** [comment]
Good catch @jakubchadim. I'm able to reproduce this; we've got it on our radar to bump some dependencies that should fix this issue for a future release of this SDK.

**Comment by zplata** [comment]
Hey @jakubchadim  - this should be addressed in `v2.3.5`, mind trying it out when you get a chance?

**Comment by zplata** [comment]
Closing, but feel free to re-open if you're still having issues after upgrading to the latest SDK version above!
