### ISSUE TITLE
Validation Error: Invalid field type: Boolean

### ISSUE THREAD

**Issue by iksi** [webflow/js-webflow-api#143]
When attempting to create a boolean field on a collection using

```
await webflow.collections.fields.create(collection.id, {
	displayName: 'Has children',
	type: 'Boolean',
})
```

The following error is returned:

```
{"error":{"statusCode":400,"body":{"message":"Validation Error: Invalid field type: Boolean","code":"validation_error","externalReference":null,"details":[]}}}
```

When creating a switch field manually, the following is returned where the field type is “Switch”:

```
 {
    "id": "6259467f67141676b0e7327f1d73446d",
    "isEditable": true,
    "isRequired": false,
    "type": "Switch",
    "slug": "has-children",
    "displayName": "Has children",
    "helpText": null,
    "validations": null
}
```

**Comment by zplata** [comment]
Thanks @iksi - we're looking into this!

**Comment by zplata** [comment]
Hi @iksi - we've since changed this to `Switch` to reflect the docs and nomenclature around this field in `v2.3.5`. Can you try with this new version?

**Comment by iksi** [comment]
@zplata Thank you, can confirm that has been resolved.
