### ISSUE TITLE
webflow.collections.fields.delete is missing

### ISSUE THREAD

**Issue by Paroca72** [webflow/js-webflow-api#159]
Hello,

Inside Fields class can found "create" and "update" but "delete" method is missing

Thanks

**Comment by zplata** [comment]
Thanks @Paroca72 for flagging - we will get this fixed in the next update

**Comment by dsinghvi** [comment]
@Paroca72 this method is now available. Here's a [link](https://github.com/webflow/js-webflow-api/blob/2f92f2921cab6171fada1e2899d4f2270e815351/src/api/resources/collections/resources/fields/client/Client.ts#L189-L192). 

Let us know if you still have any issues!
