### ISSUE TITLE
Too many request when I try to publish the website

### ISSUE THREAD

**Issue by Paroca72** [webflow/js-webflow-api#161]
Hello,

When trying to publish the Website using 
```
await webflow.sites.publish(process.env.WEBFLOW_SITE_ID, {
                customDomains: ["..."],
            });
```

I got back an error as following:
```
Error publishing Webflow website: Error: TooManyRequestsError
Status code: 429
Body: {
  "message": "Too Many Requests",
  "code": "too_many_requests",
  "externalReference": null,
  "details": []
}
```

My plan is CMS so I should not have problem about the request number.
Note that I can create Collection without any request number issue.

Thanks

**Comment by zplata** [comment]
Hey @Paroca72 - note that regardless of your plan, the Site Publish endpoint has a specific rate limit of [one publish per minute](https://docs.developers.webflow.com/data/reference/rate-limits-1#endpoint-specific-limits)

**Comment by zplata** [comment]
Closing, feel free to open a new issue if you have issues with the endpoint (w.r.t. limitations mentioned above)
