### ISSUE TITLE
createItem requires an item ID in the request but that doesn't make sense

### ISSUE THREAD

**Issue by mattho-merge** [webflow/js-webflow-api#168]
The createItem function takes in a collection Item in the request which has a required field for ID but this doesn't make sense since we're trying to create the item so it won't have an ID yet
![CleanShot 2024-09-17 at 13 35 56](https://github.com/user-attachments/assets/af8f29ee-2028-4cd5-a410-f3066138c9f5)

**Comment by zplata** [comment]
Hey @mattho-merge , yep, we're aware of this limitation. It's a weird quirk coming from translating the OpenAPI spec to the SDK but we're prioritizing trying to get it resolved.

In the meantime to unblock, I suggest using either the `createItem` call which works around this limitation, or using a direct call to the endpoint. I'll update this thread once we have a new version of the SDK that doesn't have this `id` limitation. Apologies for the inconvenience!
