### ISSUE TITLE
Migration to v2 | CMS Operations Problems

### ISSUE THREAD

**Issue by Maxwell2022** [webflow/js-webflow-api#183]
> [!NOTE] 
> I'd like to start by saying that I found it very unfortunate that there are no migration guides from V1 to V2. There is so many breaking changes that it would haven been very useful. I understand this API is in **_"preview"_** but that doesn't mean your customers are irrelevant to the public API you are providing. The only mention of this migration was in the README [but it's been deleted in a recent commit](https://github.com/webflow/js-webflow-api/commit/0d715fdbb0bf1d33dd6aa601b343630f08316c58). A specific `MIGRATION.md` would be very valuable.

## Create collection items

It seems that the [Options](https://github.com/webflow/js-webflow-api/blame/0d715fdbb0bf1d33dd6aa601b343630f08316c58/src/api/resources/collections/resources/items/client/Client.ts#L187) required to create an item in a collection is requiring an `id` when [the actual API documentation is not](https://developers.webflow.com/data/reference/cms/collection-items/staged-items/create-item), **it's not even an option**. If I had to guess I'd say the types are incorrect in all the create methods in this SDK.

<img width="587" alt="image" src="https://github.com/user-attachments/assets/c2644cf7-430e-4565-934f-d75d798eb696">

<img width="509" alt="image" src="https://github.com/user-attachments/assets/95c00f85-4635-4d65-a45e-7a44fe1be83f">

**Comment by dsinghvi** [comment]
@Maxwell2022 we're just about to release v2.5.0 which should fix this issue!

**Comment by Maxwell2022** [comment]
There is a missing bulk delete items in this SDK too, I'll check v2.5.0

**Comment by dsinghvi** [comment]
<img width="881" alt="Screenshot 2024-12-04 at 4 43 07 AM" src="https://github.com/user-attachments/assets/d51da924-5a0b-47bb-994b-990ebedf72e1">

@Maxwell2022 these methods should be available in 2.5.0 -- please let us know if you still have issues

**Comment by dsinghvi** [comment]
Additionally you should have no more typing issues on createItem https://github.com/webflow/js-webflow-api/blob/2f92f2921cab6171fada1e2899d4f2270e815351/src/api/resources/collections/resources/items/client/Client.ts#L206-L213
