### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by caspiano** [webflow/js-webflow-api#20]
Any plans on creating Typescript definitions for this library? It would be a nice boost to developer ergonomics.

**Comment by pestpro** [comment]
Any update on this

**Comment by gadirotenberg** [comment]
Is anyone up to merge this pull request?

**Comment by caspiano** [comment]
The silence from the webflow team here is pretty disappointing

**Comment by pestpro** [comment]
Looking into it now 

Pest Pro Rid All, LLC
Moe Meyer / Co Founder
Acquisitions / Market Development
P: (954) 247-4087 Ext: 100
E: ***@***.***

**Comment by austinrfnd** [comment]
I pinged my Webflow rep :)

**Comment by namuol** [comment]
(Reopening until we actually publish `0.5.4`)

**Comment by namuol** [comment]
Update: Version `0.5.4` is [now live on NPM](https://www.npmjs.com/package/webflow-api). You should be able to update your package to get TypeScript coverage now. Thank you for your patience!

**Comment by Jeandcc** [comment]
@namuol , Is it only me or does the version 0.5.4 not come with the declaration file ?

![image](https://user-images.githubusercontent.com/47673012/139731314-707bfae9-2ec9-4aa7-8e51-3f07c0c8af10.png)

![image](https://user-images.githubusercontent.com/47673012/139731381-944dde30-b73c-40f2-b603-ba7dd5bbd9c6.png)

Just tried installing it with Yarn, NPM, upgrading....nothing did the trick

**Comment by n-johnson** [comment]
I opened a PR with a super quick fix here: https://github.com/webflow/js-webflow-api/pull/44

cc @namuol - Hope things are going well at webflow, I think I'm somehow still subscribed to this repo so I was getting notifications  🤣
