### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by arronhunt** [webflow/js-webflow-api#22]
It looks like the last update was almost a year ago and the project has some TODOs. I would love to contribute but it looks like issues and PRs are simply ignored and I don’t want to spend my time if this codebase is being neglected.

**Comment by jlambright** [comment]
I'm curious about the support level of this project as well. I'd be more than happy to contribute if there are plans to keep this going. 

Side note: 

- OpenAPI v3 support?
- TypeScript Types? ( I actually started making some using json2ts.)

**Comment by arronhunt** [comment]
https://github.com/webflow/js-webflow-api/issues/18#issuecomment-731927464

So it looks like the Webflow team doesn't have any intention to support or work on this project. Going to close my own ticket since it's a duplicate.

**Comment by sansmischevia** [comment]
Hey everyone, we're planning on supporting better developer tooling (not just limited to the CMS API) this coming year. Your feedback is really valuable as we think through how best to sequence everything. Thanks!
