### ISSUE TITLE
Release a New Version of this Library

### ISSUE THREAD

**Issue by wokkaflokka** [webflow/js-webflow-api#39]
Many users of this library have noted that it has a minor security issue: https://github.com/webflow/js-webflow-api/pull/30

A fix for this issue has been merged into master for 6 weeks, but has not been released. Publishing a new version of this library with the included fix should resolve the majority of outstanding complaints around this library. 

As far as I can tell, CI/CD is already set up so all that is needed is someone with commit access to run `npm version patch`.

**Comment by dylangarcia** [comment]
Hi @wokkaflokka - we published v0.5.3, sorry about the delay on the actual release. Let us know if that solves the problem.

**Comment by wokkaflokka** [comment]
Thanks @dylangarcia. I can confirm that this is now fixed.
