### ISSUE TITLE
CMS API reference is incorrect

### ISSUE THREAD

**Issue by Jeandcc** [webflow/js-webflow-api#41]
In this link: https://developers.webflow.com/#get-specific-site

The example request using JS shows that the method should be `.sites`. However, by taking a look at the [actual implementation](https://github.com/webflow/js-webflow-api/blob/af4675fa4930ab92970b4aa33865e6a5aa619cd1/src/Webflow.js#L125-L129) of the code, we should use `.site({siteId})` to get information specific to a given website.

**Comment by gaastonsr** [comment]
Thanks for the report! we have updated the documentation to fix the typo.

**Comment by S-makes** [comment]
Stretched
