### ISSUE TITLE
Webflow API won't add a new live item if there are no items in the Collection

### ISSUE THREAD

**Issue by iurichiba** [webflow/js-webflow-api#50]
Hi guys,

I stumbled upon a weird bug, and I'd like to report it.

We're working on an integration with the Webflow API, and we need to clear a collection and re-add new items daily.
Everything was ok, until we started testing item creation (`createItem`) with `{live: true}` and failed again and again.

After a few tries, I figured out that it only fails if there are no items in the collection. If I first create another item **without** `{live: true}` and then try to create a new one **with** `{live: true}`, it works.

It's a weird bug, and I have no idea why it happens or if it's by design... hope it helps, though.

In the meantime, I guess we'll just have to use a dummy item and keep it staged in the beginning of each refresh cycle.
Please let me know if you manage to fix it, though!

Thanks!

**Comment by johnagan** [comment]
Weird indeed! Thank you for sharing this bug with us. 

I've passed it on the product team to investigate and I'll keep this issue open until I hear back.

**Comment by johnagan** [comment]
Update: We've filed a bug for this and will look into it. Thank you for filing it!

I'm going to close this out since it's not specific to the SDK. I'm also working on a formal place to file api-related bugs.

**Comment by dylangarcia** [comment]
Hey @iurichiba - just for some clarification, is this on a _new_ collection, with no items, that hasn't been published yet? Or is this on an existing collection, that has been published, with no items?
