### ISSUE TITLE
Allow empty `token` when initializing the library

### ISSUE THREAD

**Issue by nickfla1** [webflow/js-webflow-api#56]
## Description

Due to security reasons, our token and authorization with Webflow is handled by a **Man In The Middle** proxy, forcing us to pass a dummy (and unneeded) string as the token during initialization.

Would it be possible to add a flag to disable requiring the token on initialization? I know it's an edge case but It could be useful to other people/projects as well.

I can provide a PR if instructed with the naming convention.

Thanks!

**Comment by johnagan** [comment]
Hey @nickfla1 . You're welcome to propose a PR and we can review.
