### ISSUE TITLE
What does installer mean?

### ISSUE THREAD

**Issue by sebbASF** [webflow/js-webflow-api#66]
It's good that there is now a way to access 'GET /user', but the method name 'installer' is not at all obvious.

The description for the request is 'Basic information about the current authorized user.'.

I think it would be clearer to call the method 'current_user' or similar, rather than 'installer', which suggests something entirely different.

**Comment by johnagan** [comment]
The person that installed the app. This wouldn't be "Current User". I'm open to another name for it

**Comment by johnagan** [comment]
great! thank you for sharing the feedback 😎
