### ISSUE TITLE
Cannot access API via localhost [Uncaught TypeError]

### ISSUE THREAD

**Issue by Maybach91** [webflow/js-webflow-api#74]
Using the basic instructions to access the API like stated in the readme, i cannot make it work using it in my local environment.

I have a API Token and try to access the API via the following:
```javascript
import Webflow from 'webflow-api';

// initialize the client with the access token
const webflow = new Webflow({ token: process.env.WEBFLOW_ACCESS_TOKEN });
```

But this shows me the following console error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')`
for this line: `RedirectableRequest.prototype = Object.create(Writable.prototype);`

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1867543/201652599-191e4a6f-c165-427a-a213-799a0fd0a49f.png">

Is the reason because i’m trying to access it via localhost or is there something wrong with the package/my environment?  Using `node@v18.3.0`, `yarn@3.2.1` `webflow-api@^1.2.0` and `vite@^3.2.3`

**Comment by johnagan** [comment]
I see you mention node 18, but your error appears to be a browser error. Are you attempting to load this in the client?

**Comment by Maybach91** [comment]
> I see you mention node 18, but your error appears to be a browser error. Are you attempting to load this client-side (in browser)?

@johnagan yes, I’m trying to access it via client-side, I thought it’s possible with this library. But i know the API only works server side, right?

**Comment by johnagan** [comment]
You're exposing your access token in the client that way 😦 

If I understand what your build is, the env variables will just populate into your compiled client code
