### ISSUE TITLE
Get single site not working for some reason?

### ISSUE THREAD

**Issue by nachogoncam** [webflow/js-webflow-api#78]
`webflow.sites({ siteId: "[ SITE ID ]" })`  seems to be returning all the sites associated to the authenticated user and not the specific site for the provided id

**Comment by johnagan** [comment]
have you tried it without the `s` in `sites`, like [this](https://github.com/webflow/js-webflow-api#rate-limit)?
```javascript
webflow.site({ siteId: "[ SITE ID ]" })
```

**Comment by johnagan** [comment]
Fixed! Thank you 😎
