### ISSUE TITLE
Add live parameter to createItems method

### ISSUE THREAD

**Issue by JonathanJJudge** [webflow/js-webflow-api#8]
The API documentation allows for live publishing new content, but when adding live:true to the data, it doesn't appear to be auto-publishing the new item. Moreover the documentation for live creating items indicates a query parameter rather than in the data itself directly. Can this be added to the createItems method here in the library very soon?

**Comment by jacobwgillespie** [comment]
This should actually already be possible - I'll see about getting some documentation added.  The third argument to the `createItem` function controls the URL query params, so you should be able to do the following with `{ live: true }`:

```javascript
const webflow = new Webflow({ token: api_token });

// Promise <Item>
const item = webflow.createItem({
  collectionId: '580e63fc8c9a982ac9b8b745',
  fields: {
    // The data
  },
}, { live: true });

item.then(i => console.log(i));
```

**Comment by janpapenbrock** [comment]
I feel like this is not working properly.

I'm calling like this:

```
return webFlowApi.createItem({ collectionId: myCollectionId, fields: item }, { live: true });
```

And I am receiving this error:

```
WebflowError: NotFound: Collection not found: null
```

I debugged into the calls and it looks like the POST URL is built just like shown [in the documentation](https://developers.webflow.com/#create-new-live-collection-item), i.e. `https://api.webflow.com/collections/<my-id>/items?live=true`, but I still get the error response back (404 from the server).
