### ISSUE TITLE
Configuration params

### ISSUE THREAD

**Issue by SalGnt** [webflow/js-webflow-api#81]
Do you think a `params`  object can be added to the client options?

**Comment by johnagan** [comment]
Can you describe your use-case?

**Comment by SalGnt** [comment]
Sure. Due to security reasons the interaction with Webflow is handled by a **Man In The Middle** proxy, with its own endpoint (that doesn't always include `api.`) that is used by the SDK on the client.

Also, having optional `params` can help provide other possible data that such proxy needs.

Thank you!

The same scenario applies to #81.
