### ISSUE TITLE
Pagination data missing

### ISSUE THREAD

**Issue by AndreasMaros** [webflow/js-webflow-api#90]
I'd been using this library pinned to version 0.6.0 for a while and now upgraded to the lastest version in order to benefit from not having to publish the entire site in order to publish changed CMS items (which I've still had to implement workarounds for due to #89).

As the new methods (I suspect since the TS rewrite) do not return the API's response data anymore (but rather arrays or instances of `Item` objects), the pagination data from the API response is not accessible anymore.
This means that when querying `collection.items({ offset: 0, limit: 100 })` I get no feedback about the `total` amount of items in the collection. I could also not find a simple alternative way of querying the item count of a collection – which means that these methods are broken, as they will only ever return the first 100 items of a collection, with no hint as to whether there are any more.

One hacky workaround would be to make another request for `collection.items({ offset: 100, limit: 100 })` whenever exactly 100 items have been returned. This is, however, a waste of my precious requests given the unpredictable and tight rate limiting applied to the API (considering items can only be created, updated or deleted individually one per request).

I'm currently working around this by calling `Webflow.get` with `/collections/${collectionId}/items?offset=${offset}&limit=${limit}` manually and parsing `response.data`, but that sort of defeats the purpose of using this SDK in the first place.

**Comment by dsinghvi** [comment]
Hey @AndreasMaros this is now fixed in `v2.1.1` of the Webflow SDK!
